<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<table class="generic-table meal-list">
    <caption>Home</caption>
    <tbody>
        <!-- Code HTML à écrire -->
        <div>

	<h1>Les amis de la nature</h1><br>
	<p>Bienvenue sur le site les amis de la nature. Nous sommes une association à but non lucratif qui a pour but de la preservation et la valorisation de notre environnement naturel au travers d'un certain nombre d'actions et d'evenements.
	En effet,nous organisations des actions par le biais d'ateliers educatifs:jardinage,decouverte,recyclage,cuisine,nettoyage de primptemps mais aussi des evenementiels : visite musee,randonnées, pic-nic en fôret,decouverte marine afin de de mieux preserver notre milieu naturel et d'avoir les bons gestes ecologiques pour le sauvergarder et assurer sa pérennité.
	Par ailleurs nous collaborons avec plusieurs partenaires économiques qui ont été selectionnés pour leur respect et leurs pratiques pour la sauvergarde de notre milieu naturel.
	Vous pouvez devenir membre après  avoir remplie un formulaire et vous  etre acquitté  d'une cotisation annuelle de 55 euros ou venir sur place,nous vous acceuillerons avec plaisir.
	<a class="button member" href="<?=$requestUrl?>/user/register">Vous voulez devenir membre?</a></p><br>

</div>

    </tbody>
</table>