<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Projet</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/presentation.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
   
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <table class="shower">

    <tr class="welcome">
        <td class="button connect"><a href="<?=$requestUrl?>">Accueil</a></td>

        <?php if (array_key_exists( 'firstname', $_SESSION ) == false) {?>
        
                          
            <td class="button connect"><a href="<?=$requestUrl?>/user/login">Connexion</a></td>
            
                       
            <td class=" button evenement"><a href="<?=$requestUrl?>/consult/event">Calendrier evenements</a></td>
            <td class="button partners"><a href= "<?=$requestUrl?>/consult/partner">Partenaires</a></td>  
     
     
     <?php } else {?>           
       
        
       
        
            <td class=" button evenement"><a href="<?=$requestUrl?>/consult/event">Calendrier evenements</a></td>
            <td class="button partners"><a href= "<?=$requestUrl?>/consult/event">Partenaires</a></td>   
            <td class="button button-primary" ><a href="<?=$requestUrl?>/user/logout">Déconnexion</a>
           
        
    <?php  } ?>

    </tr>
        <!-- Code HTML/PHP à écrire -->
    </table>
</nav>

<main class="fond">
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template']; ?>
</main>

<!-- Pied de page commun -->
<footer>
    <a href="">NOUS CONTACTER</a>

</footer>

<!-- Code principal JavaScript de l'application -->

 <script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>   
           
        
       
            
    