<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>traducteur</title>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans">

</head>
<body >
    <header>
        <h1 >Traducteur Anglais-Français</h1>
    </header>
   
    
<form  action="traducteur.php" method="POST">
      <label for="mot">Mot:</label>
            <input type="text" name="mot" id="mot">
      <label for="traduction">Sens de traduction :</label>      
            <select name="traduction">
              <option value="FA">Francais vers Anglais</option>
              <option value="AF" >Anglais vers Français</option>
            </select>

       <input type="submit" value="traduire">       

    
</form>

</body>

</html>
